// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: org/books/add/svc_add.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Org.Books.Add {

  /// <summary>Holder for reflection information generated from org/books/add/svc_add.proto</summary>
  public static partial class SvcAddReflection {

    #region Descriptor
    /// <summary>File descriptor for org/books/add/svc_add.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SvcAddReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtvcmcvYm9va3MvYWRkL3N2Y19hZGQucHJvdG8SDW9yZy5ib29rcy5hZGQa",
            "G2dvb2dsZS9wcm90b2J1Zi9lbXB0eS5wcm90bxofb3JnL2Jvb2tzL3NoYXJl",
            "ZC9tc2dfYm9vay5wcm90bzJJCgpBZGRTZXJ2aWNlEjsKB0FkZEJvb2sSFi5v",
            "cmcuYm9va3Muc2hhcmVkLkJvb2saFi5nb29nbGUucHJvdG9idWYuRW1wdHki",
            "AGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Org.Books.Shared.MsgBookReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
