// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: org/books/list/svc_list.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Org.Books.List {

  /// <summary>Holder for reflection information generated from org/books/list/svc_list.proto</summary>
  public static partial class SvcListReflection {

    #region Descriptor
    /// <summary>File descriptor for org/books/list/svc_list.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SvcListReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1vcmcvYm9va3MvbGlzdC9zdmNfbGlzdC5wcm90bxIOb3JnLmJvb2tzLmxp",
            "c3QaHW9yZy9ib29rcy9saXN0L21zZ19saXN0LnByb3RvMlcKC0xpc3RTZXJ2",
            "aWNlEkgKCUxpc3RCb29rcxIbLm9yZy5ib29rcy5saXN0Lkxpc3RSZXF1ZXN0",
            "Ghwub3JnLmJvb2tzLmxpc3QuTGlzdFJlc3BvbnNlIgBiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Org.Books.List.MsgListReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
